### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by mxmilkiib** [spolu/dwm.vim#1]
Would be handy. Apparently suckless.vim does this, but I haven't tried it yet. Ctrl-w | Ctrl-w _ to fullscreen leaves the other windows present in a crushed form.

**Comment by spolu** [comment]
as you said on HN C-F does restore state right?

**Comment by spolu** [comment]
In any case C-W | is a pain in the ass in dwm.vim context so we have to add a fullscreen mode.

**Comment by spolu** [comment]
Proposing C-L to switch between fullscreen and tiled mode

**Comment by mxmilkiib** [comment]
C-F resets, yes. Cool beans, as long as I can remap it :) I'd really love to align my Awesome, Tmux and Vim key bindings to match now.

**Comment by spolu** [comment]
You can remap as you want (see the dwm.vim file). Yep it's all about finding the right bindings for your setting :)

**Comment by spolu** [comment]
In fact I believe it's fixed by `C-W |` and then `C-F`, but we could map `C-W |` on `C-L`...

**Comment by jhwee** [comment]
I think you mean `C-W |` and then `C-H`?

**Comment by spolu** [comment]
yes! :)

**Comment by spolu** [comment]
added a fullscreen mode with `C-L`
