### ISSUE TITLE
Window terminology?

### ISSUE THREAD

**Issue by matze** [spolu/dwm.vim#13]
I am currently preparing a help file for dwm.vim. Now to explain the mechanics to the user, we should have a convention how to call certain things in dwm.vim. This is especially important because the idea of Vim windows is usually not easily grasped by Vim newcomers.

I'd propose the following scheme: The two sides are called _master pane_ and _stacked pane_. Therefore, a _focused window_ is located in the master pane (yes, technically they are the same) and all others in the stacked pane. A window that is not focused in the master pane but has the input focused is called _active_.

To my best knowledge this should only affect issue #12.

**Comment by spolu** [comment]
That's a great idea! I personally find your terminology perfectly clear.

**Comment by mitnk** [comment]
+1 for @matze 's idea.

How about move the window to _master pane_ position when switching windows (by pushing `C-J` or `C-K`). Then we wouldn't need the _active_ to be defined :)

**Comment by spolu** [comment]
@mitnk that would be weird. It's handy to go into a stacked window make a quick yank or edit and come back to your master pane

**Comment by mitnk** [comment]
@spolu Yeah, you are right.

For #12, I can change the setting name to `dwm_master_pane_width`.

**Comment by matze** [comment]
Thanks, then I will update the docs and issue a pull request soon.

**Comment by matze** [comment]
I guess this one can then be closed.

**Comment by spolu** [comment]
definitely!
