### ISSUE TITLE
Opening a help window and keeping it open

### ISSUE THREAD

**Issue by Industrial** [spolu/dwm.vim#19]
This isn't such a dwm.vim related question per-se but I accidentally bumped into it while using dwm.vim;

If I open a help file e.g. :help options.txt it will create a horizontal split. Why won't the buffer just stay in the buffer list until I delete or wipe it? If after opening the help I do any window management e.g. C-n then the temporary help buffer is gone.

**Comment by lmarburger** [comment]
I have to assume this has something to do with calling `only!` to arrange the buffers. I learned yesterday that `:new` buffers are unlisted when hidden. It makes sense to me that a help buffer would receive the same treatment.

I tested how help windows are handled using the technique described in #18. From what I can tell they're handled just like any other visible window.

**Comment by spolu** [comment]
Normally solved by #18 just merged right?

**Comment by Industrial** [comment]
Correct.
