### ISSUE TITLE
Support for tabs

### ISSUE THREAD

**Issue by Perry3D** [spolu/dwm.vim#25]
Hello,

first i want to say thanks for this great plugin. Well done :).

But i have a problem when using tabs with this plugin. 
For example: after starting gvim i open 3 files with dwm. Then i open a new tab (:tabnew). If i press <C-N> now the three files from the first tab are also opened in the second tab.

That's really annoying cause i'm used to work with tabs.

**Comment by lmarburger** [comment]
I'm in the same boat. This issue is covered in #3 and will be fixed if and when #18 is merged.

**Comment by spolu** [comment]
solved by #18
