### ISSUE TITLE
Working with tabs

### ISSUE THREAD

**Issue by mxmilkiib** [spolu/dwm.vim#3]
:tabnew (and then opening 3 files) and then Ctrl-f copes buffer windows from all tabs into the current tab. It would be great to manage tabs as seperate workspaces.

**Comment by spolu** [comment]
Yep. completely agreed that's an entire refactoring work that has to be done asap.

**Comment by treyhunner** [comment]
:+1: This feature would allow me to use dwm.vim.  I frequently open a dozen files in a single vim session which makes dwm.vim unusable currently.

**Comment by spolu** [comment]
It's on its way...
https://github.com/afriggeri/dwm.vim/blob/move-around/plugin/dwm.vim
and #18

**Comment by spolu** [comment]
sovled by #18
