### ISSUE TITLE
Invert some of the mapping

### ISSUE THREAD

**Issue by teoljungberg** [spolu/dwm.vim#31]
- C-H should 'move the split' to the left, and C-L to the right.
- C-J should do CCW and not CW. C-K should do C-W 

This makes more sense in how the keys are mapped, that might differ from DWM as a philosophy tho.

The project looks stellar now, nice done!

**Comment by spolu** [comment]
I have to agree with `<C-H>` / `<C-L>` but disagree with  `<C-J>` / `<C-K>` as `J` lets you go down your stacked buffers.

**Comment by teoljungberg** [comment]
Well, if we just change the mapping - that shouldn't change the behaviour, just the keys pressed.

I'm formulating a pull-req, fill refer it to here

**Comment by spolu** [comment]
This was closed by #32
