### ISSUE TITLE
Problem with ack.vim

### ISSUE THREAD

**Issue by rlisowski** [spolu/dwm.vim#54]
I use [ack.vim](https://github.com/mileszs/ack.vim plugin) it show search result in the quickfix window but with dwm.vim enabled quickfix window appears on the right instead of the bottom of current buffer.

Is there any way to fix that?

**Comment by spolu** [comment]
Well we have to figure out if there is anyway to detect ack.vim window. Is it tagged? If so you should be able to have a fix based on #50 #51 #52

**Comment by rlisowski** [comment]
There is buftype == 'quickfix'  and filetype == 'qf', but I don't know how use that and I think I didn't explain exactly what my problem is.
This is what I expect:
![image](https://f.cloud.github.com/assets/7737/1838470/ac0707d4-745d-11e3-9ab5-31a8a72f8467.png)
This is what I get with dwm:
![image](https://f.cloud.github.com/assets/7737/1838472/b85bba16-745d-11e3-9971-09ebd01233f7.png)

**Comment by spolu** [comment]
Yep it makes sense. I'll try to find some time to test and find a solution but I'm pretty swamped these days. @FlashKorten or @n4kz may have an opinion on this?

**Comment by n4kz** [comment]
Actual behaviour is similar to dwm itself. We can modify autocommand to ignore quickfix buffer but first layout update will move it to stack.

**Comment by n4kz** [comment]
Same problem in #24 and #49
I'm looking for solution but cannot promise anything.

**Comment by spolu** [comment]
@n4kz that would be awesome! Would be glad to help though I don't have much free cycle these days. Let me know!

**Comment by rlisowski** [comment]
Works for me.
