### ISSUE TITLE
How to disable Ctrl+J?

### ISSUE THREAD

**Issue by llinfeng** [spolu/dwm.vim#58]
I tried out dwm but the fact that Ctrl+J is occupied is the major reason for me to uninstall the package. Overall, I think this is a handy plugin. Thanks for the effort.

So, is there a way to re-map the <C-J>? Actually, I want to map all the local key-bindings to be <C-S-X>. I believe this would avoid any further overlapping. 

All the best, 
- Linfeng

**Comment by spolu** [comment]
Hi!

You can remap all the keys in your own config file:

See: https://github.com/spolu/dwm.vim/blob/master/plugin/dwm.vim#L196
