### ISSUE TITLE
Disable for NERDTree

### ISSUE THREAD

**Issue by dagadbm** [spolu/dwm.vim#65]
Hello,

Is it possible to change the behaviour to disable the dwm when you have nerd tree?

Its a bit weird when you use nerd tree and you open a file. NERDTree just goes to the right stack window which makes it a bit awkward in terms of behaviour if I have to open multiple files.

Regards,

dagadbm.

![image](https://cloud.githubusercontent.com/assets/16737095/12854632/a8e920c6-cc32-11e5-8b27-d97ac432a790.png)

**Comment by ghost** [comment]
Copy and paste https://github.com/spolu/dwm.vim/issues/41#issuecomment-11232486 . From now on do **NOT** press enter to open files in NERDTree, instead select the wanted file and press `s` to make a split. Tested with NERDTreeToggle.
